frontend:
  replicas: 2
  image: 658140043880.dkr.ecr.us-east-2.amazonaws.com/frontend-service:v1

course:
  replicas: 1
  image: 658140043880.dkr.ecr.us-east-2.amazonaws.com/course-service:v1

student:
  replicas: 1
  image: 658140043880.dkr.ecr.us-east-2.amazonaws.com/student-service:v1

service:
  port: 80

bluegreen:
  activeColor: blue

postgres:
  username: postgres
  password: postgres123
  database: coursedb
  image:
    repository: postgres
    tag: "15"
  service:
    port: 5432
  storage: 5Gi
